// ! To get All Projects
export const GET_PROJECT_LOADING = "GET_PROJECT_LOADING";
export const GET_PROJECT_SUCCESSFUL = "GET_PROJECT_SUCCESSFUL";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";
// ! To get Single Project
export const GET_SINGLE_PROJECT_LOADING = "GET_SINGLE_PROJECT_LOADING";
export const GET_SINGLE_PROJECT_SUCCESSFUL = "GET_SINGLE_PROJECT_SUCCESSFUL";
export const GET_SINGLE_PROJECT_FAILURE = "GET_SINGLE_PROJECT_FAILURE";

// ! For login
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
