// ! To get All Projects
export const GET_PROJECT_LOADING = "GET_PROJECT_LOADING";
export const GET_PROJECT_SUCCESSFUL = "GET_PROJECT_SUCCESSFUL";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";
// ! To get Single Project
export const GET_SINGLE_PROJECT_LOADING = "GET_SINGLE_PROJECT_LOADING";
export const GET_SINGLE_PROJECT_SUCCESSFUL = "GET_SINGLE_PROJECT_SUCCESSFUL";
export const GET_SINGLE_PROJECT_FAILURE = "GET_SINGLE_PROJECT_FAILURE";

// ! For login
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// ! DISCUSSION FORUM CONSTANTS
// ? POST A QUESTION CONSTANTS
export const POST_QUESTION_LOADING = "POST_QUESTION_LOADING";
export const POST_QUESTION_SUCCESSFUL = "POST_QUESTION_SUCCESSFUL";
export const POST_QUESTION_FAILED = "POST_QUESTION_FAILED";

// ! DISCUSSION FORUM CONSTANTS
// ? GET ALL QUESTIONS
export const GET_QUESTIONS_LOADING = "GET_QUESTIONS_LOADING";
export const GET_QUESTIONS_SUCCESSFUL = "GET_QUESTIONS_SUCCESSFUL";
export const GET_QUESTIONS_FAILED = "GET_QUESTIONS_FAILED";

// ! To get Single Question
export const GET_SINGLE_QUESTION_LOADING = "GET_SINGLE_QUESTION_LOADING";
export const GET_SINGLE_QUESTION_SUCCESSFUL = "GET_SINGLE_QUESTION_SUCCESSFUL";
export const GET_SINGLE_QUESTION_FAILURE = "GET_SINGLE_QUESTION_FAILURE";
