export const teachersAccount = [
  {
    firstName: "Dr. Khalil-ur-Rehman",
    lastName: "Khoumbhati",
    designation: "Professor (Dean, FET)",
    email: "khalil.khoumbati@usindh.edu.pk",
    password: "abcd123",
  },
  {
    firstName: "Dr. Lachman Das",
    lastName: "Dhomeja",
    designation: "Professor",
    email: "lachhman@usindh.edu.pk",
    password: "abcd123",
  },
  {
    firstName: "Mr. Imran Anwar",
    lastName: "Ujjan",
    designation: "Assistant Professor",
    email: "imran.ujan@usindh.edu.pk",
    password: "abcd123",
  },
  {
    firstName: "Dr. Kamran Taj",
    lastName: "Pathan",
    designation: "Professor",
    email: "kamran.taj@usindh.edu.pk",
    password: "abcd123",
  },
  {
    firstName: "Dr. Bisharat Rasool",
    lastName: "Memon",
    designation: "Assistant Professor",
    email: "bisharat.memon@usindh.edu.pk",
    password: "abcd123",
  },
  {
    firstName: "Dr. Abdul Waheed",
    lastName: "Mahesar",
    designation: "Associate Professor",
    email: "waheed.mahessar@usindh.edu.pk",
    password: "abcd123",
  },
  {
    firstName: "Dr. Zeeshan",
    lastName: "Bhatti",
    designation: "Associate Professor",
    email: "zeeshan.bhatti@usindh.edu.pk",
    password: "abcd123",
  },
  {
    firstName: "Mr. Kamran",
    lastName: "Dahri",
    designation: "Assistant Professor",
    email: "kamran.dahri@usindh.edu.pk",
    password: "abcd123",
  },
];
